// Generated by gencpp from file unity_robotics_demo_msgs/FingerPosMsg.msg
// DO NOT EDIT!


#ifndef UNITY_ROBOTICS_DEMO_MSGS_MESSAGE_FINGERPOSMSG_H
#define UNITY_ROBOTICS_DEMO_MSGS_MESSAGE_FINGERPOSMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unity_robotics_demo_msgs
{
template <class ContainerAllocator>
struct FingerPosMsg_
{
  typedef FingerPosMsg_<ContainerAllocator> Type;

  FingerPosMsg_()
    : pos_1(0.0)
    , pos_2(0.0)  {
    }
  FingerPosMsg_(const ContainerAllocator& _alloc)
    : pos_1(0.0)
    , pos_2(0.0)  {
  (void)_alloc;
    }



   typedef float _pos_1_type;
  _pos_1_type pos_1;

   typedef float _pos_2_type;
  _pos_2_type pos_2;





  typedef boost::shared_ptr< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> const> ConstPtr;

}; // struct FingerPosMsg_

typedef ::unity_robotics_demo_msgs::FingerPosMsg_<std::allocator<void> > FingerPosMsg;

typedef boost::shared_ptr< ::unity_robotics_demo_msgs::FingerPosMsg > FingerPosMsgPtr;
typedef boost::shared_ptr< ::unity_robotics_demo_msgs::FingerPosMsg const> FingerPosMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator1> & lhs, const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator2> & rhs)
{
  return lhs.pos_1 == rhs.pos_1 &&
    lhs.pos_2 == rhs.pos_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator1> & lhs, const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_robotics_demo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ebc591d2739c3a5a1e50adfe2a7e48b";
  }

  static const char* value(const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ebc591d2739c3a5ULL;
  static const uint64_t static_value2 = 0xa1e50adfe2a7e48bULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_robotics_demo_msgs/FingerPosMsg";
  }

  static const char* value(const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_1\n"
"float32 pos_2\n"
;
  }

  static const char* value(const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_1);
      stream.next(m.pos_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FingerPosMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_robotics_demo_msgs::FingerPosMsg_<ContainerAllocator>& v)
  {
    s << indent << "pos_1: ";
    Printer<float>::stream(s, indent + "  ", v.pos_1);
    s << indent << "pos_2: ";
    Printer<float>::stream(s, indent + "  ", v.pos_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_ROBOTICS_DEMO_MSGS_MESSAGE_FINGERPOSMSG_H
